# Generated by Django 6.0.3 on 2026-03-12 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('telegram', 'Telegram'), ('dingtalk', '钉钉')], max_length=20, verbose_name='通知渠道')),
                ('bot_token', models.CharField(blank=True, max_length=100, verbose_name='Bot Token')),
                ('chat_id', models.CharField(blank=True, max_length=50, verbose_name='Chat ID')),
                ('webhook', models.URLField(blank=True, verbose_name='Webhook URL')),
                ('secret', models.CharField(blank=True, max_length=100, verbose_name='密钥')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '通知配置',
                'verbose_name_plural': '通知配置',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='店铺名称')),
                ('app_id', models.CharField(max_length=64, unique=True, verbose_name='App ID')),
                ('app_key', models.CharField(max_length=64, verbose_name='App Key')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '店铺',
                'verbose_name_plural': '店铺',
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True, verbose_name='配置键')),
                ('value', models.TextField(verbose_name='配置值')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置',
            },
        ),
        migrations.CreateModel(
            name='StockFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_type', models.CharField(choices=[('sale', '销售'), ('purchase', '采购'), ('transfer', '调拨'), ('adjust', '调整'), ('return', '退货'), ('other', '其他')], max_length=20, verbose_name='流水类型')),
                ('flow_number', models.CharField(max_length=100, verbose_name='流水号')),
                ('product_barcode', models.CharField(max_length=50, verbose_name='商品条码')),
                ('product_name', models.CharField(max_length=200, verbose_name='商品名称')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('balance', models.IntegerField(verbose_name='库存余额')),
                ('created_time', models.DateTimeField(verbose_name='创建时间')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_flows', to='core.store')),
            ],
            options={
                'verbose_name': '库存流水',
                'verbose_name_plural': '库存流水',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='LowStockRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_barcode', models.CharField(max_length=50, verbose_name='商品条码')),
                ('product_name', models.CharField(max_length=200, verbose_name='商品名称')),
                ('current_stock', models.IntegerField(verbose_name='当前库存')),
                ('min_stock', models.IntegerField(default=0, verbose_name='预警库存')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='low_stock_records', to='core.store')),
            ],
            options={
                'verbose_name': '低库存记录',
                'verbose_name_plural': '低库存记录',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='ApiUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(max_length=100, verbose_name='API 名称')),
                ('call_count', models.IntegerField(default=0, verbose_name='调用次数')),
                ('call_time', models.DateTimeField(auto_now_add=True, verbose_name='调用时间')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_usages', to='core.store')),
            ],
            options={
                'verbose_name': 'API 使用统计',
                'verbose_name_plural': 'API 使用统计',
                'ordering': ['-call_time'],
            },
        ),
        migrations.CreateModel(
            name='InventoryCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(verbose_name='缓存数据')),
                ('timestamp', models.DateTimeField(verbose_name='缓存时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caches', to='core.store')),
            ],
            options={
                'verbose_name': '库存缓存',
                'verbose_name_plural': '库存缓存',
                'ordering': ['-timestamp'],
                'unique_together': {('store',)},
            },
        ),
    ]
