# Generated by Django 6.0.3 on 2026-03-13 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(verbose_name='商品数据')),
                ('updated_at', models.DateTimeField(verbose_name='更新时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_caches', to='core.store')),
            ],
            options={
                'verbose_name': '商品缓存',
                'verbose_name_plural': '商品缓存',
                'ordering': ['-updated_at'],
                'unique_together': {('store',)},
            },
        ),
    ]
