# Generated by Django 6.0.3 on 2026-03-13 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_productcache'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clerk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_number', models.CharField(max_length=20, unique=True, verbose_name='工号')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('can_view_price', models.BooleanField(default=False, verbose_name='能否查看价格')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clerks', to='core.store', verbose_name='所属门店')),
            ],
            options={
                'verbose_name': '店员',
                'verbose_name_plural': '店员',
                'ordering': ['store', 'job_number'],
            },
        ),
        migrations.CreateModel(
            name='ClerkApiUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('call_count', models.IntegerField(default=0, verbose_name='调用次数')),
                ('last_call_time', models.DateTimeField(auto_now=True, verbose_name='最后调用时间')),
                ('clerk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_usages', to='core.clerk', verbose_name='店员')),
            ],
            options={
                'verbose_name': '店员API使用',
                'verbose_name_plural': '店员API使用',
                'ordering': ['-date'],
                'unique_together': {('clerk', 'date')},
            },
        ),
    ]
