# Generated by Django 6.0.3 on 2026-03-13 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_clerk_clerkapiusage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50, verbose_name='订单ID')),
                ('items', models.JSONField(verbose_name='商品明细')),
                ('total_quantity', models.IntegerField(default=0, verbose_name='总数量')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('status', models.CharField(default='success', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('clerk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='core.clerk', verbose_name='店员')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='core.store', verbose_name='门店')),
            ],
            options={
                'verbose_name': '进货单',
                'verbose_name_plural': '进货单',
                'ordering': ['-created_at'],
            },
        ),
    ]
