# Generated by Django 6.0.3 on 2026-03-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_purchaseorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='can_login',
            field=models.BooleanField(default=True, verbose_name='允许登录'),
        ),
    ]
