# Generated by Django 6.0.3 on 2026-03-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_can_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='purchase_images/%Y/%m/', verbose_name='图片'),
        ),
    ]
