# Generated by Django 6.0.3 on 2026-03-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_purchase_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clerkapiusage',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='clerkapiusage',
            name='clerk',
        ),
        migrations.AlterUniqueTogether(
            name='inventorycache',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='inventorycache',
            name='store',
        ),
        migrations.RemoveField(
            model_name='lowstockrecord',
            name='store',
        ),
        migrations.AlterUniqueTogether(
            name='productcache',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='productcache',
            name='store',
        ),
        migrations.RemoveField(
            model_name='stockflow',
            name='store',
        ),
        migrations.DeleteModel(
            name='SystemConfig',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='总金额'),
        ),
        migrations.DeleteModel(
            name='ClerkApiUsage',
        ),
        migrations.DeleteModel(
            name='InventoryCache',
        ),
        migrations.DeleteModel(
            name='LowStockRecord',
        ),
        migrations.DeleteModel(
            name='ProductCache',
        ),
        migrations.DeleteModel(
            name='StockFlow',
        ),
    ]
